version: '2'
services:
    #PHP + Apache
    php:
        build: ./php
        # mapowanie lokalnego katalogu na path kontenera
        volumes:
            - ./html:/var/www/html
        ports:
            - "8080:8080"
        environment:
            # Host kontenera, patrz w READMY
            XDEBUG_CONFIG: remote_host=172.20.0.3
        # czekaj na mysql
        depends_on:
            - mysql
    # Baza
    mysql:
        build: ./mysql
        # Mapowanie portu kontenera na port localhost
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=docker
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_PASSWORD=root
    varnish:
        image: million12/varnish
        environment:
            VCL_CONFIG: ./varnish/varnish.vcl
            CACHE_SIZE: 64m
